version: 1
services:
  - type: web
    name: your-service-name  # Replace with your service name
    env: node
    plan: starter
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    runtime: node
    nodeVersion: "16.x"  # or your desired version