version: 1
services:
  - type: web
    name: ArToe
    env: python
    plan: starter
    buildCommand: |
      # Clear any existing Poetry environment/cache if Render mistakenly detects it
      rm -rf $HOME/.cache/pypoetry $HOME/.poetry
      # Install dependencies from requirements.txt
      pip install -r requirements.txt
      # Install and build the frontend
      npm install --prefix frontend
      npm run build --prefix frontend
      # Collect static files and run migrations
      python manage.py collectstatic --noinput
      python manage.py migrate
    runtime: python
    pythonVersion: "3.11"
    startCommand: gunicorn artoe.wsgi:application --bind 0.0.0.0:8000