version: 1
services:
  - type: web
    name: ArToe
    env: python
    plan: starter
    buildCommand: |
      source venv/bin/activate
      pip install -r requirements.txt
      npm install --prefix frontend
      npm run build --prefix frontend
      python manage.py collectstatic --noinput
      python manage.py migrate
    runtime: python
    pythonVersion: "3.11"
    startCommand: |
      source venv/bin/activate && \
      gunicorn artoe.wsgi:application --bind 0.0.0.0:8000
databases:
  - name: artoe-db
    envVar: DATABASE_URL
    postgresVersion: "14"
