version: 1
services:
  - type: web
    name: ArToe
    env: python
    plan: starter
    buildCommand: |
      rm -rf $HOME/.cache/pypoetry $HOME/.poetry
      pip install -r requirements.txt
      npm install --prefix frontend
      npm run build --prefix frontend
      python manage.py collectstatic --noinput
      python manage.py migrate
    runtime: python
    pythonVersion: "3.11"
    startCommand: python -m gunicorn artoe.wsgi:application --bind 0.0.0.0:8000