# Generated by Django 5.1.2 on 2024-10-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sneaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_description", models.TextField()),
                ("long_description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("main_image", models.ImageField(upload_to="sneakers/main/")),
                ("other_images", models.JSONField()),
                ("size", models.CharField(max_length=10)),
            ],
        ),
    ]
